# Universal Windows Platform
# Build a Universal Windows Platform application using Visual Studio.
# Add steps that test and distribute the app, save build artifacts, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'VS2017-Win2016'

variables:
  solution: 'windows/**/*.sln'
  pfxPath:  'windows/**/*/pfx'
  buildPlatform: 'x86|x64|ARM'
  buildConfiguration: 'Release'
  appxPackageDir: '$(build.artifactStagingDirectory)\AppxPackages\'

steps:

- task: NuGetToolInstaller@0

- script: |
    certutil.exe -f -user -p password -importPFX $(pfxPath) NoRoot

- task: NodeTool@1
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install and build'

- task: NuGetCommand@3
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@4
  inputs:
    platform: 'x86'
    solution: '$(solution)'
    configuration: '$(buildConfiguration)'
    msbuildArgs: '/p:AppxBundlePlatforms="$(buildPlatform)" /p:AppxPackageDir="$(appxPackageDir)" /p:AppxBundle=Always /p:UapAppxPackageBuildMode=StoreUpload'
