# Universal Windows Platform
# Build a Universal Windows Platform application using Visual Studio.
# Add steps that test and distribute the app, save build artifacts, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'VS2017-Win2016'

variables:
  solution: 'windows/**/*.sln'
  cert: 'windows/**/*.pfx'
  buildPlatform: 'x86|x64|ARM'
  buildConfiguration: 'Release'
  appxPackageDir: '$(build.artifactStagingDirectory)\AppxPackages\\'

steps:

#- script: echo $(Build.Repository.LocalPath)\windows
#
#- task: NuGetToolInstaller@0

#- script: |
#    certutil.exe -f -user -p password -importPFX D:/a/1/s/windows/testReactNativeWindowsApp/testReactNativeWindowsApp_TemporaryKey.pfx NoRoot
#
#- task: NodeTool@0
#  inputs:
#    versionSpec: '8.x'
#  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install and build'

#- task: NuGetCommand@2
#  inputs:
#    restoreSolution: '$(solution)'

- script: DIR node_modules\react-native-windows\Yoga\csharp


#- task: VSBuild@1
#  inputs:
#    platform: 'x86'
#    solution: '$(solution)'
#    configuration: '$(buildConfiguration)'
#    msbuildArgs: '/p:AppxBundlePlatforms="$(buildPlatform)" /p:AppxPackageDir="$(appxPackageDir)" /p:AppxBundle=Always /p:UapAppxPackageBuildMode=StoreUpload'
